
# "/api/" ==> W4F\GameBundle\Controller\HomeController:indexAction()
w4f_game_homepage:
    path:     /
    defaults: { _controller: W4fGameBundle:Home:index }
    

w4f_game_subscribe:
    path: /user
    defaults: { _controller: W4fGameBundle:User:addUser }
    requirements:
        _method:  POST