
# "/api/" ==> W4F\GameBundle\Controller\HomeController:indexAction()
w4f_game_homepage:
    path:     /
    defaults: { _controller: W4fGameBundle:Home:index }
    

w4f_game_subscribe:
    path: /subscribe
    defaults: { _controller: W4fGameBundle:User:subscribe }