parameters:
#    w4f_game.example.class: W4f\GameBundle\Example

services:
    w4f_game.UoW:
        class: W4f\GameBundle\Model\UnitOfWork
        arguments: [ @doctrine.orm.entity_manager ]
    
#    w4f_game.example:
#        class: %w4f_game.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
